<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Customer IDV</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7a8a3bcc-a3d1-435b-87fe-d4a805b2a3c3</testSuiteGuid>
   <testCaseLink>
      <guid>95db4a14-e226-44d7-82be-aeab2f126a31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>1</defaultValue>
         <description></description>
         <id>e6ffc84a-cb4c-42b6-97ee-b3f30cbdb741</id>
         <masked>false</masked>
         <name>loanreq_id</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/TC02_Customer_Idv</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>42b87ebc-c074-4028-a053-b5c44c10c06c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/NRIC</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>84138c54-dea4-42c8-97e8-c421fd36fb98</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Dummy</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47a1ffb5-b5fb-4c4a-9b4b-0562da622b98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>864a7d18-ccf8-4aae-a2d2-b1f6c62138a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>546a6b9c-d8ac-4ad4-aab5-765c39a1b1f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e14acf6f-0b8f-4e8e-91bb-987100130ec0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45f7b3ed-d252-43da-967d-65cb360956a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f839e526-87b7-44b7-8db3-056063024603</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>648fb72b-ae39-4dcd-bc0e-8aa2c84d3239</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>097e7c0a-38d4-4315-a2a4-f76c55acb19d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>84138c54-dea4-42c8-97e8-c421fd36fb98</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Dummy</value>
         <variableId>1feeb5cb-bf63-4601-a51f-c70b79f1d0f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6ffc84a-cb4c-42b6-97ee-b3f30cbdb741</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa2096be-6e53-4835-aac5-d586888fbaeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04913836-8c31-4683-a9f7-43ad6a51c395</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c06a84b2-1a9e-4b4d-8920-cba8b95e563c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
