<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Customer Profile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>273bb6ba-2f55-43b2-ae9e-ac945098b055</testSuiteGuid>
   <testCaseLink>
      <guid>ab7e399c-8f07-4200-b8f3-c075b57374a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC03_Customer_Profile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0af24cf2-a677-4126-b5a9-6d7f8410c549</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/NRIC</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a669b08-f0c4-412b-af90-2be308f1b192</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a7ea82f-dcbb-433c-bad0-6750832d9629</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afb7a45d-e65a-4792-ba1b-e34d8a68b753</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8434a8d5-b853-478b-a0e2-e1df1be1e6f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3daa494d-ef61-4f0f-92e3-b3819f2f0ce7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51dfbf9d-7875-4938-88f3-5b1fac4c73dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f76fb1e6-e53d-43d5-9c66-372643f0f2bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f6922be-10b7-4434-bd9d-f053a179cdff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>184a966e-a6ae-4fe7-b4a6-b8a08860fd50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfa3f62a-7141-4a23-8ae8-c421eae0bd6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b4cc0ca-df91-4638-afc9-0467f7907f55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0af24cf2-a677-4126-b5a9-6d7f8410c549</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Customer_Idv</value>
         <variableId>6a803c78-430b-46f4-9835-cd762efc0b52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3eb833e4-d661-4796-9d7e-acbd00cab2cc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
