<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>New Nric</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1ef7244b-450e-4087-9ce2-64f423052332</testSuiteGuid>
   <testCaseLink>
      <guid>7c1e7b3c-7524-45f5-a8fc-f51f7b1aebfe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC01_NEW_NRIC</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4ad20f7f-6ed9-4e2d-a63a-cd4bea9c6be7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/NRIC</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e4373107-aa1f-4b21-ab51-15a9e4be6606</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/test1</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bd549d0c-76e8-4178-a7c3-76a78fcc7749</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Dummy</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf3c2846-e189-46ac-9503-ae1a9005efec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aa137c0-4e6a-41f6-b983-08890fd4a56f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e5c3b1f-9a8f-4402-a0f2-bda8b45a023d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff356ec5-7845-4285-b842-268a0f4a1032</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad03d9ba-0dea-4e6d-b386-9996fc25bfbd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45ee78ed-cb3e-4bc5-80b0-94d552a3bf70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33014786-af17-472e-9c0f-cedd0eea283d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b528388-ec4d-4bab-8498-2cd49469046f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bd549d0c-76e8-4178-a7c3-76a78fcc7749</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Dummy</value>
         <variableId>b0c3a409-5675-489e-9d88-6a456b3820f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>290a2ea8-df34-4889-9174-484b64265ac0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59f47dc7-9d39-4a6d-b2f1-cad5ecfe2c7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6bbcd81-deb8-4317-ade7-e654329c7c0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0360e88-0518-490f-90b3-f757ff612ab0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
